import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowLeft, BriefcaseBusiness, Check, Copy, FileText, Globe2, MessageSquareText, Search, Sparkles } from "lucide-react";

export const Route = createFileRoute("/criar")({ component: JobPass });

type Application={company:string;role:string;status:string};
const countries=["Espanha","Portugal","Itália","França","Alemanha","Irlanda","Reino Unido","Canadá","Estados Unidos","Austrália","Outro"];
const jobs=["Hotelaria","Restaurante","Construção","Limpeza","Logística","Vendas","Atendimento","Tecnologia","Administrativo","Saúde","Outro"];
const portals:any={Espanha:["SEPE","EURES","InfoJobs","LinkedIn","Indeed"],Portugal:["IEFP","EURES","Net-Empregos","LinkedIn","Indeed"]};
const terms:any={Restaurante:["camarero/a","ayudante de cocina","hostelería"],Hotelaria:["recepcionista","housekeeping","hotel"],Construção:["peón de obra","ayudante de construcción","construcción"]};

function JobPass(){
 const [step,setStep]=useState(0),[destination,setDestination]=useState("Espanha"),[origin,setOrigin]=useState("Brasil"),[job,setJob]=useState("Restaurante"),[language,setLanguage]=useState("Espanhol"),[name,setName]=useState(""),[experience,setExperience]=useState(""),[cvMode,setCvMode]=useState("zero"),[vacancy,setVacancy]=useState(""),[tab,setTab]=useState("cv"),[apps,setApps]=useState<Application[]>([]);
 const profile=name||"Seu nome"; const localTerms=terms[job]||[job.toLowerCase(),"emprego "+job.toLowerCase(),"vaga "+job.toLowerCase()];
 const intro=useMemo(()=> destination==="Espanha" ? `Hola, buenas tardes. Me llamo ${profile}. Estoy buscando trabajo en el área de ${job.toLowerCase()} y quería saber si podría enviarles mi currículum.` : `Olá, boa tarde. Chamo-me ${profile}. Procuro trabalho na área de ${job.toLowerCase()} e gostaria de saber se posso enviar o meu currículo.`,[destination,profile,job]);
 const summary=experience.trim()? `Profissional com experiência em ${job.toLowerCase()}, com foco em atendimento, organização, colaboração e adaptação a novos ambientes. ${experience.trim()}`:`Profissional interessado em oportunidades na área de ${job.toLowerCase()}, com disponibilidade para aprender, colaborar e adaptar-se aos processos da equipa.`;
 const copy=(x:string)=>navigator.clipboard?.writeText(x);
 if(step<3) return <div className="min-h-dvh bg-ivory text-ink"><header className="border-b border-ink/10 px-5 py-4 sm:px-8"><Link to="/" className="inline-flex items-center gap-2 text-sm"><ArrowLeft className="size-4"/> JobPass</Link></header><main className="mx-auto max-w-3xl px-5 py-12 sm:px-8"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-clay">Etapa {step+1} de 3</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-ink/10"><div className="h-full bg-forest" style={{width:`${((step+1)/3)*100}%`}}/></div></div>
 {step===0&&<section><h1 className="text-4xl font-semibold tracking-tight">Para onde você está indo?</h1><p className="mt-2 text-warm-muted">Isso define idioma, formato do CV e recursos locais.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><label className="rounded-xl border border-ink/10 bg-paper p-4">País de origem<input className="mt-2 w-full rounded-lg border border-ink/10 bg-ivory p-3" value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label className="rounded-xl border border-ink/10 bg-paper p-4">Destino<select className="mt-2 w-full rounded-lg border border-ink/10 bg-ivory p-3" value={destination} onChange={e=>setDestination(e.target.value)}>{countries.map(x=><option key={x}>{x}</option>)}</select></label></div></section>}
 {step===1&&<section><h1 className="text-4xl font-semibold tracking-tight">O que você procura?</h1><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{jobs.map(x=><button key={x} onClick={()=>setJob(x)} className={`rounded-xl border p-4 text-left ${job===x?"border-forest bg-forest text-paper":"border-ink/10 bg-paper"}`}>{x}</button>)}</div><label className="mt-5 block">Idioma de candidatura<input className="mt-2 w-full rounded-lg border border-ink/10 bg-paper p-3" value={language} onChange={e=>setLanguage(e.target.value)}/></label></section>}
  {step===2&&<section><h1 className="text-4xl font-semibold tracking-tight">Conte o que você já tem.</h1><div className="mt-6 grid gap-3 sm:grid-cols-4">{[["pdf","Enviar PDF"],["foto","Enviar foto"],["colar","Colar texto"],["zero","Começar do zero"]].map(([v,l]:[string,string])=><button key={v} onClick={()=>setCvMode(v)} className={`rounded-xl border p-4 text-sm ${cvMode===v?"border-forest bg-forest text-paper":"border-ink/10 bg-paper"}`}>{l}</button>)}</div><div className="mt-6 grid gap-4"><input className="rounded-lg border border-ink/10 bg-paper p-3" placeholder="Seu nome" value={name} onChange={e=>setName(e.target.value)}/><textarea className="min-h-36 rounded-lg border border-ink/10 bg-paper p-3" placeholder={cvMode==="colar"?"Cole aqui seu currículo ou histórico profissional":"Conte sua experiência real. Não precisa escrever bonito; o JobPass organiza sem inventar nada."} value={experience} onChange={e=>setExperience(e.target.value)}/>{(cvMode==="pdf"||cvMode==="foto")&&<input type="file" accept={cvMode==="pdf"?"application/pdf":"image/*"} className="rounded-lg border border-dashed border-ink/20 bg-paper p-4"/>}</div></section>}
 <div className="mt-9 flex justify-between"><button disabled={step===0} onClick={()=>setStep(s=>s-1)} className="rounded-full border border-ink/15 px-5 py-3 disabled:opacity-30">Voltar</button><button onClick={()=>step===2?setStep(3):setStep(s=>s+1)} className="rounded-full bg-forest px-6 py-3 font-medium text-paper">{step===2?"Gerar meu JobPass":"Continuar"}</button></div></main></div>;
 if(step===3) return <div className="min-h-dvh bg-ivory text-ink"><header className="border-b border-ink/10 bg-paper/80 px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link to="/" className="font-semibold">JobPass</Link><span className="text-xs text-warm-muted">{destination} · {job}</span></div></header><main className="mx-auto grid max-w-5xl items-center gap-10 px-5 py-10 sm:px-8 sm:py-16 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-clay">Tudo pronto</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Seu JobPass para {destination} está pronto.</h1><p className="mt-4 max-w-xl text-base leading-7 text-warm-muted">Terminamos sua preparação com base no que você informou. Agora você pode liberar o pacote completo.</p><div className="mt-7 space-y-3">{["Currículo adaptado + ATS","Versão em "+language,"Carta e mensagens de candidatura","Preparação para entrevista","Sites, termos de busca e plano de 7 dias"].map(x=><div key={x} className="flex items-center gap-3 rounded-xl border border-ink/10 bg-paper px-4 py-3 text-sm"><Check className="size-5 text-forest"/>{x}</div>)}</div><div className="mt-8 rounded-2xl border border-ink/10 bg-paper p-6"><p className="text-sm font-semibold text-forest">JobPass Essencial</p><div className="mt-2 flex items-end gap-2"><span className="text-4xl font-semibold tracking-tight">€12,90</span><span className="pb-1 text-sm text-warm-muted">pagamento único</span></div><button onClick={()=>setStep(4)} className="mt-5 w-full rounded-full bg-forest px-6 py-3 font-medium text-paper hover:bg-forest-deep">Liberar meu JobPass — €12,90</button><p className="mt-3 text-center text-[11px] text-warm-muted">Checkout ainda não conectado nesta versão de teste.</p></div></div><img src="/jobpass-preview-locked.svg" alt="Preview do JobPass pronto antes da liberação" className="w-full rounded-3xl shadow-[var(--shadow-paper)]"/></main></div>;
 const tabs=[["cv","Currículo",FileText],["vaga","Adaptar vaga",Search],["mensagens","Mensagens",MessageSquareText],["entrevista","Entrevista",Sparkles],["empregos","Empregos",Globe2],["candidaturas","Candidaturas",BriefcaseBusiness]];
 return <div className="min-h-dvh bg-ivory text-ink"><header className="sticky top-0 z-10 border-b border-ink/10 bg-paper/90 backdrop-blur"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-4 sm:px-8"><Link to="/" className="font-semibold">JobPass</Link><div className="text-right"><p className="text-sm font-medium">{destination} · {job}</p><p className="text-[11px] text-warm-muted">{origin} → {destination} · {language}</p></div></div></header><main className="mx-auto max-w-[1280px] px-5 py-8 sm:px-8"><div className="mb-7"><p className="text-sm text-warm-muted">Olá, {profile}.</p><h1 className="text-3xl font-semibold tracking-tight">Seu plano para {destination} está pronto.</h1></div><nav className="mb-7 flex gap-2 overflow-x-auto pb-2">{tabs.map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm ${tab===id?"bg-forest text-paper":"border border-ink/10 bg-paper"}`}><Icon className="size-4"/>{label}</button>)}</nav>
 {tab==="cv"&&<Panel title="Currículo adaptado"><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border border-ink/10 bg-paper p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-forest">Perfil profissional</p><h2 className="mt-3 text-2xl font-semibold">{profile}</h2><p className="mt-1 text-sm text-warm-muted">{job} · {destination}</p><p className="mt-6 leading-7">{summary}</p><div className="mt-6 border-t border-ink/10 pt-5"><b>Experiência informada</b><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-warm-muted">{experience||"Adicione sua experiência para personalizar esta seção."}</p></div></div><div className="space-y-3"><Card t="Versão ATS" d="Estrutura limpa, sem elementos que prejudiquem leitura automática."/><Card t={"Versão em "+language} d="Adaptação linguística mantendo os fatos do seu histórico."/><button onClick={()=>window.print()} className="w-full rounded-xl bg-clay p-4 font-medium text-paper">Exportar / imprimir PDF</button></div></div></Panel>}
 {tab==="vaga"&&<Panel title="Adaptar para uma vaga"><p className="mb-4 text-sm text-warm-muted">Cole a vaga. O JobPass usa apenas fatos que você informou; não cria experiências ou competências.</p><textarea value={vacancy} onChange={e=>setVacancy(e.target.value)} className="min-h-44 w-full rounded-xl border border-ink/10 bg-paper p-4" placeholder="Cole aqui a descrição da vaga…"/><div className="mt-4 rounded-xl border border-ink/10 bg-paper p-5"><b>Adaptação orientada à vaga</b><p className="mt-2 text-sm leading-6 text-warm-muted">{vacancy?"Priorize no currículo os requisitos da vaga que tenham correspondência real com sua experiência. Reforce "+job.toLowerCase()+" no resumo e use a terminologia da descrição sem adicionar qualificações não informadas.":"Cole uma descrição para receber as orientações de adaptação."}</p></div></Panel>}
  {tab==="mensagens"&&<Panel title="Mensagens prontas">{[["WhatsApp / presencial",intro],["E-mail",`Olá, meu nome é ${profile}. Estou me candidatando a oportunidades na área de ${job.toLowerCase()} em ${destination}. Encaminho meu currículo para consideração. Fico à disposição para conversar sobre minha experiência e disponibilidade.`],["LinkedIn",`Olá! Sou ${profile} e estou buscando oportunidades em ${job.toLowerCase()} em ${destination}. Gostaria de me conectar e acompanhar oportunidades na área.`]].map(([t,x]:[string,string])=><div key={t} className="mb-3 rounded-xl border border-ink/10 bg-paper p-5"><div className="flex justify-between gap-3"><b>{t}</b><button onClick={()=>copy(x)}><Copy className="size-4"/></button></div><p className="mt-3 text-sm leading-6 text-warm-muted">{x}</p></div>)}</Panel>}
 {tab==="entrevista"&&<Panel title="Kit entrevista"><div className="grid gap-3 md:grid-cols-2">{["Fale um pouco sobre você.","Por que quer trabalhar conosco?","Qual sua experiência nesta área?","Como você lida com clientes ou pressão?","Qual sua disponibilidade?","Por que está buscando trabalho em "+destination+"?"].map((q,i)=><Card key={q} t={(i+1)+". "+q} d="Responda com fatos do seu histórico, em 30–60 segundos. Seja específico e não invente resultados."/>)}</div><div className="mt-5 rounded-xl bg-sand/40 p-5"><b>Modo treino</b><p className="mt-2 text-sm text-warm-muted">A base está pronta para receber o coach por voz em uma V2, com correção de vocabulário, gramática, clareza e naturalidade.</p></div></Panel>}
 {tab==="empregos"&&<Panel title={"Encontrar empregos em "+destination}><div className="grid gap-4 md:grid-cols-2"><div><h3 className="font-semibold">Portais para começar</h3><div className="mt-3 space-y-2">{(portals[destination]||["EURES","LinkedIn","Indeed"]).map((x:string)=><div key={x} className="rounded-lg border border-ink/10 bg-paper p-3">{x}</div>)}</div></div><div><h3 className="font-semibold">Termos de busca</h3><div className="mt-3 flex flex-wrap gap-2">{localTerms.map((x:string)=><span key={x} className="rounded-full bg-forest/10 px-3 py-2 text-sm text-forest">{x}</span>)}</div><h3 className="mt-6 font-semibold">Plano de 7 dias</h3><ol className="mt-3 space-y-2 text-sm text-warm-muted">{["Finalizar CV e perfis","Mapear 20 vagas","Enviar 5 candidaturas personalizadas","Contato direto com empresas","Revisar respostas e ajustar buscas","Nova rodada de candidaturas","Follow-up e organização da semana"].map((x,i)=><li key={x}>{i+1}. {x}</li>)}</ol></div></div><p className="mt-6 rounded-lg border border-ink/10 p-3 text-xs text-warm-muted">Informações migratórias, documentos obrigatórios e direito ao trabalho devem ser confirmados em fontes oficiais atualizadas do país de destino.</p></Panel>}
 {tab==="candidaturas"&&<Panel title="Minhas candidaturas"><button onClick={()=>setApps([...apps,{company:"Nova empresa",role:job,status:"Enviar"}])} className="mb-4 rounded-full bg-forest px-4 py-2 text-sm text-paper">+ Adicionar candidatura</button><div className="space-y-2">{apps.length===0&&<p className="text-sm text-warm-muted">Nenhuma candidatura ainda.</p>}{apps.map((a,i)=><div key={i} className="grid gap-2 rounded-xl border border-ink/10 bg-paper p-4 sm:grid-cols-[1fr_1fr_auto]"><input value={a.company} onChange={e=>setApps(apps.map((x,j)=>j===i?{...x,company:e.target.value}:x))} className="bg-transparent font-medium"/><input value={a.role} onChange={e=>setApps(apps.map((x,j)=>j===i?{...x,role:e.target.value}:x))} className="bg-transparent text-sm"/><select value={a.status} onChange={e=>setApps(apps.map((x,j)=>j===i?{...x,status:e.target.value}:x))} className="rounded-lg border border-ink/10 bg-ivory p-2 text-sm">{["Enviar","Enviado","Entrevista","Resposta"].map(x=><option key={x}>{x}</option>)}</select></div>)}</div></Panel>}
 <section className="mt-8 rounded-2xl border border-clay/20 bg-clay/10 p-6"><div className="flex items-start gap-3"><Check className="mt-1 size-5 text-clay"/><div><b>JobPass Pro · estrutura preparada</b><p className="mt-1 text-sm text-warm-muted">CVs e adaptações ilimitadas, traduções, entrevista simulada e histórico avançado podem ser liberados por assinatura. Checkout fica desacoplado para integração com o provedor de pagamento escolhido.</p></div></div></section></main></div>
}
function Panel({title,children}:{title:string;children:any}){return <section><h2 className="mb-5 text-2xl font-semibold tracking-tight">{title}</h2>{children}</section>}
function Card({t,d}:{t:string;d:string}){return <div className="rounded-xl border border-ink/10 bg-paper p-5"><b>{t}</b><p className="mt-2 text-sm leading-6 text-warm-muted">{d}</p></div>}
